telegram:
  api_id: xxxxxxx
  api_hash: "xxxxxxxxxxxxxxxxxb2536da610"
  session_name: "translate"  # 支持修改，可以默认不更改
  my_tg_id: xxxxxxxxx  # 你的Telegram用户ID，主要用于识别本人id，仅本人可用命令动态增删翻译规则

### 默认翻译源，可选 openai 或 deeplx
default_translate_source: "openai"
### 翻译引擎一
deeplx:
  base_urls:
    - "https://api.deeplx.org/可以用linux.do的码子1/translate"
    - "https://api.deeplx.org/可以用linux.do的码子2/translate"
    - "https://api.deeplx.org/可以用linux.do的码子3/translate"
### 翻译引擎二
openai:
  # 支持多个API地址和Key，轮询防止失效，需按顺序对应
  base_urls:
    - "https://api.xxx.com/v1"
    - "https://中转APIURL地址/v1"
    - "https://官方API——URL地址/v1"
  api_keys:
    - "sk-111111111111"
    - "sk-222222222222"
    - "sk-333333333333"
  models:
    - "gpt-4o"
    - "deepseek-r1-0528"
    - "gemini-2.0-flash"
# 引擎顺序轮询，调用失效次数达到阈值后（留空默认3次）禁用
deeplx_fail_threshold: 4
openai_fail_threshold: 4

# fasttext 语言识别配置
fasttext:
  enabled: true
  confidence_threshold: 0.8
  fallback_enabled: true
  # 新增：模型文件路径，建议默认即可
  model_path: "lid.176.bin"

# 语言检测增强配置
lang_detect_short_text_unknown: true
lang_detect_proper_nouns:
  - openwebui
  - chatgpt
  - midjourney
  - gpt
  - sdwebui
  - stable-diffusion
# 新增：默认翻译方向规则
self_default_rule: "zh,en"      # 如使用编号，等同于下面规则池编号，等价于 "zh,en"
other_default_rule: "en,zh"     # 如使用编号，等同于下面规则池编号，等价于 "en,zh"

# 可选规则池(编号一定是字符串)
# 支持管理/维护常用组合，格式：编号: "源1|源2,目1|目2"，每对为一组，代码默认取第一组使用(扩展请修改parse_rule_pair)
# 多组举例："fr|ru,en|zh" 表示可支持法语/俄语源翻成英文/中文；如只配对一组就是"zh,en"或"en,zh"
translate_rules:
  "1": "zh,en"                 # 中->英
  "2": "en,zh"                 # 英->中
  "3": "zh|en,zh|en"           # 中英互译
  "4": "ru,zh|ar"              # 俄译中、阿拉伯语
  "5": "fr|ru,en|zh"           # 多源/多目标写法（仅内部约定，主流程取第一组做默认）
  "6": "fr|ru|en,en|zh"        # 分别按照有效规则计入，且已有重复规则合并
  "7": "*,en|zh"               # 删除规则时，可以删除匹配目标语言为en和zh的任意源语言组合
  "7": "en|zh,*"               #删除规则时，可以删除匹配源语言为en和zh的任意目标语言组合
    
ignore_words:
  # 以下为不需要翻译的英文指令或关键词，支持完全匹配和部分匹配（如以.开头的命令）
  # 可根据实际需求增删
  - "cd"
  - "60s"
  - ".de"
  - ".id"
  - "id"
  - "我的id"
  - "已删除"
  - "群id"
  - ".fy"
  - "fy"
  - "ai"
  - "gg"
  - "gp"
  - "gc"
  - "gcp"
  - "md5转换"
  - "ikun"
  - "IKUN"
  - "ping"
  - "aichatgpt"
  - "aichatgptc"
  - "aidraw"
  - "aidss"
  - "aidsc"
  - ".tgde"
  - "aigeminis"
  - "aigeminic"
  - "aigeminip"
  - "mp"
  - "mpd"
  - "ainewgpt"
  - "ainewgptc"
  - "ainewgptp"
  - "ainewdraw"

