telegram:
  api_id: xxxxxxx
  api_hash: "xxxxxxxxxxxxxxxxxb2536da610"
  session_name: "translate"  # 支持修改，可以默认不更改
  my_tg_id: xxxxxxxxx  # 你的Telegram用户ID，主要用于识别本人id，仅本人可用命令动态增删翻译规则

### 默认翻译源，可选 openai 或 deeplx
default_translate_source: "openai"
### 翻译引擎一
deeplx:
  base_urls:
    - "https://api.deeplx.org/可以用linux.do的码子1/translate"
    - "https://api.deeplx.org/可以用linux.do的码子2/translate"
    - "https://api.deeplx.org/可以用linux.do的码子3/translate"
### 翻译引擎二
openai:
  # 支持多个API地址和Key，轮询防止失效，需按顺序对应
  base_urls:
    - "https://api.xxx.com/v1"
    - "https://中转APIURL地址/v1"
    - "https://官方API——URL地址/v1"
  api_keys:
    - "sk-111111111111"
    - "sk-222222222222"
    - "sk-333333333333"

# 新增：默认翻译方向规则，在不加规则的指令下，使用默认翻译规则
self_default_rule: "zh,en"        # 如使用编号，等同于下面规则池编号，等价于 "zh,en"，推荐直接填规则
other_default_rule: "en,zh"       # 如使用编号，等同于下面规则池编号，等价于 "en,zh"

# 规则池，用于展示规则写法，可以自己增加规则，写法支持，一对一、一对多、多对一、多对多规则都可以
translate_rules:
  "1": "zh,en"  # 中->英
  "2": "en,zh"  # 英->中
  "3": "fr,en"
  "4": "ru,zh"
  "5": "fr|ru,en|zh"    # 多源/多目标写法（仅内部约定，主流程取第一组做默认）
  "6": "fr|ru,en"    # 多源/多目标写法（仅内部约定，主流程取第一组做默认）
  "7": "fr,en|zh"    # 多源/多目标写法（仅内部约定，主流程取第一组做默认）

ignore_words:
  # 以下为不需要翻译的英文指令或关键词，支持完全匹配和部分匹配（如以.开头的命令）
  # 可根据实际需求增删，列举为同时使用了bncr无界bot项目，避免指令冲突，或者误翻译
  - "cd"
  - "60s"
  - ".de"
  - ".id"
  - "id"
  - "我的id"
  - "群id"
  - "fy"
  - "ai"
  - "gg"
  - "gp"
  - "gc"
  - "gcp"
  - "md5转换"
  - "ikun"
  - "IKUN"
  - "ping"
  - "aichatgpt"
  - "aichatgptc"
  - "aidraw"
  - "aidss"
  - "aidsc"
  - ".tgde"
  - "aigeminis"
  - "aigeminic"
  - "aigeminip"
  - "mp"
  - "mpd"
  - "ainewgpt"
  - "ainewgptc"
  - "ainewgptp"
  - "ainewdraw"
